[package]
name = "billion"
version = "0.1.0"
edition = "2021"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.6"

[dependencies]
env_logger = "0.11.5"
fs_extra = "1.3.0"
log = "0.4.22"
rand = "0.8.5"
sysinfo = "0.35.0"
talna = { path = ".." }
